CREATE TABLE ProductCatalog (
    ProductID INT PRIMARY KEY,
    Name VARCHAR(255),
    Description TEXT,
    Price DECIMAL(10, 2),
    QuantityInStock INT,
    MinimumQuantityInStock INT,
    MaximumQuantityInStock INT,
    SupplierID INT,
    CategoryID INT,
    Brand VARCHAR(255),
    Model VARCHAR(255),
    SKU VARCHAR(50),
    UPC VARCHAR(50),
    EAN VARCHAR(50),
    ISBN VARCHAR(50),
    Color VARCHAR(50),
    Size VARCHAR(50),
    Weight DECIMAL(10, 2),
    Height DECIMAL(10, 2),
    Width DECIMAL(10, 2),
    Depth DECIMAL(10, 2),
    Material VARCHAR(255),
    UsageInstructions TEXT,
    WarrantyInformation TEXT,
    MainImageUrl VARCHAR(255),
    SecondaryImageUrls TEXT,
    DemonstrationVideoUrl VARCHAR(255),
    CreationDate DATETIME,
    LastModifiedDate DATETIME,
    AvailableForSale BIT,
    VisibleInStore BIT,
    AverageRating DECIMAL(3, 2),
    NumberOfRatings INT,
    NumberOfReviews INT,
    -- ... additional columns as needed ...
    FOREIGN KEY (SupplierID) REFERENCES Suppliers(SupplierID),
    FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID)
);
